const Map<String, String> getString = {
    'tab1': 'Профиль',
    'tab2': 'Настройки',
    'carouselheadertitle': 'У вас подключено',
    'carouselheadersubtitle': 'Подписки, автоплатежи и сервисы на которые вы подписались',
    'carouselname1': 'СберПрайм',
    'carouseltitle1': 'Платёж 9 июля',
    'carouselsubtitle': '199 ₽ в месяц',
    'carouselname2': 'Переводы',
    'carouseltitle2': 'Автопродление 21 августа',
    'listheadertitle': 'Тарифы и лимиты',
    'listheadersubtitle': 'Для операций в Сбербанк Онлайн',
    'listtitle1': 'Изменить суточный лимит',
    'listsubtitle1': 'На платежи и переводы',
    'listtitle2': 'Переводы без комиссии',
    'listsubtitle2': 'Показать остаток в этом месяце',
    'listtitle3': 'Информация о тарифах и лимитах',
    'listsubtitle3': '',
    'chipsheadertitle': 'Интересы',
    'chipsheadersubtitle': 'Мы подбираем истории и предложения по темам, которые вам нравятся',
    'snackbarclose': 'Закрыть',
    'snackbarlogout': 'Выйти',
    'profilename': 'Екатерина',
};
